# Extraction Patterns for Rule-based Extraction
# Regular expressions and patterns for extracting invoice fields

patterns:
  # Invoice Number Patterns
  invoice_number:
    - pattern: "(?:Invoice|Bill|Receipt)\\s*(?:No|Number|#)?:?\\s*([A-Z0-9/-]+)"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.9
    
    - pattern: "INV[-/]?(\\d{4,})"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.85
    
    - pattern: "(?:Tax)?\\s*Invoice:?\\s*([A-Z0-9/-]+)"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.8
  
  # Date Patterns
  invoice_date:
    - pattern: "(?:Date|Dated|Invoice Date):?\\s*(\\d{1,2}[/-]\\d{1,2}[/-]\\d{2,4})"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.9
    
    - pattern: "(\\d{1,2}[/-]\\d{1,2}[/-]\\d{2,4})"
      flags: ""
      group: 1
      confidence: 0.7
    
    - pattern: "(\\d{1,2}\\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\\s+\\d{4})"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.85
  
  # Company Name Patterns
  company_name:
    - pattern: "^([A-Z][A-Za-z0-9\\s&.,-]+(?:Ltd|Limited|Pvt|Private|Inc|Corp|Company))"
      flags: "MULTILINE"
      group: 1
      confidence: 0.9
    
    - pattern: "(?:From|Seller|Vendor):?\\s*([A-Z][A-Za-z0-9\\s&.,-]+)"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.8
  
  # GST Number Patterns
  gst_number:
    - pattern: "(?:GSTIN|GST No|GST):?\\s*([0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1})"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.95
    
    - pattern: "([0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1})"
      flags: ""
      group: 1
      confidence: 0.85
  
  # PAN Number Patterns
  pan_number:
    - pattern: "(?:PAN|PAN No):?\\s*([A-Z]{5}[0-9]{4}[A-Z]{1})"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.95
    
    - pattern: "([A-Z]{5}[0-9]{4}[A-Z]{1})"
      flags: ""
      group: 1
      confidence: 0.7
  
  # FSSAI Number Patterns
  fssai_number:
    - pattern: "(?:FSSAI|Lic No|License No):?\\s*(\\d{14})"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.95
    
    - pattern: "(\\d{14})"
      flags: ""
      group: 1
      confidence: 0.6
  
  # Total Amount Patterns
  total:
    - pattern: "(?:Total|Grand Total|Net Amount):?\\s*(?:Rs\\.?|₹)?\\s*([\\d,]+\\.?\\d*)"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.9
    
    - pattern: "(?:Amount Payable):?\\s*(?:Rs\\.?|₹)?\\s*([\\d,]+\\.?\\d*)"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.85
  
  # Subtotal Patterns
  subtotal:
    - pattern: "(?:Sub Total|Subtotal|Sub-Total):?\\s*(?:Rs\\.?|₹)?\\s*([\\d,]+\\.?\\d*)"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.9
  
  # Tax Amount Patterns
  tax:
    - pattern: "(?:CGST|SGST|IGST|GST|Tax):?\\s*(?:@\\s*\\d+%)?\\s*(?:Rs\\.?|₹)?\\s*([\\d,]+\\.?\\d*)"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.85
    
    - pattern: "(?:Tax Amount):?\\s*(?:Rs\\.?|₹)?\\s*([\\d,]+\\.?\\d*)"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.9
  
  # Email Patterns
  email:
    - pattern: "([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})"
      flags: ""
      group: 1
      confidence: 0.95
  
  # Phone Patterns
  phone:
    - pattern: "(?:Phone|Tel|Mobile|Contact):?\\s*(?:\\+91)?\\s*([6-9]\\d{9})"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.9
    
    - pattern: "(?:\\+91|91)?\\s*([6-9]\\d{9})"
      flags: ""
      group: 1
      confidence: 0.7
  
  # Address Patterns
  address:
    - pattern: "(?:Address):?\\s*([A-Za-z0-9\\s,.-]+(?:India|PIN|\\d{6}))"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.8
  
  # HSN/SAC Code Patterns
  hsn_sac_code:
    - pattern: "(?:HSN|SAC|HSN/SAC):?\\s*(\\d{4,8})"
      flags: "IGNORECASE"
      group: 1
      confidence: 0.9
    
    - pattern: "(\\d{4,8})"
      flags: ""
      group: 1
      confidence: 0.5

# Table Extraction Patterns
table_patterns:
  # Item table headers
  headers:
    item_description:
      - "Item"
      - "Description"
      - "Particulars"
      - "Goods"
      - "Product"
    
    quantity:
      - "Qty"
      - "Quantity"
      - "Nos"
      - "Units"
    
    rate:
      - "Rate"
      - "Price"
      - "Unit Price"
      - "Rate/Unit"
    
    amount:
      - "Amount"
      - "Total"
      - "Value"
    
    hsn:
      - "HSN"
      - "HSN Code"
      - "SAC"
    
    weight:
      - "Weight"
      - "Wt"
      - "Net Wt"
  
  # Row patterns
  row_pattern: "^(.+?)\\s+(\\d+(?:\\.\\d+)?)\\s+(?:Rs\\.?|₹)?\\s*([\\d,]+\\.?\\d*)\\s+(?:Rs\\.?|₹)?\\s*([\\d,]+\\.?\\d*)$"

# Contextual Patterns
contextual:
  # Buyer/Seller identification
  buyer_section:
    markers:
      - "Bill To"
      - "Buyer"
      - "Sold To"
      - "Customer"
    end_markers:
      - "Ship To"
      - "Invoice Details"
      - "Date"
  
  seller_section:
    markers:
      - "Seller"
      - "Vendor"
      - "From"
      - "Supplier"
    end_markers:
      - "Bill To"
      - "Buyer"
  
  # Payment details section
  payment_section:
    markers:
      - "Payment Details"
      - "Bank Details"
      - "Account Details"
    fields:
      - "Bank Name"
      - "Account Number"
      - "IFSC"
      - "Branch"

# Field Proximity Rules
proximity:
  # Fields that usually appear together
  grouped_fields:
    - fields: ["invoice_number", "invoice_date"]
      max_distance: 50
    
    - fields: ["subtotal", "tax", "total"]
      max_distance: 100
    
    - fields: ["gst_number", "company_name"]
      max_distance: 200

# Post-processing Rules
post_processing:
  # Clean extracted values
  cleaning:
    invoice_number:
      - remove: ["Invoice", "No", ":", "#"]
      - strip: true
      - uppercase: false
    
    company_name:
      - strip: true
      - remove_extra_spaces: true
    
    amounts:
      - remove: [",", "Rs", "Rs.", "₹", "$"]
      - strip: true
      - to_float: true
    
    phone:
      - remove: ["+91", "91", "-", " "]
      - strip: true
    
    gst_number:
      - uppercase: true
      - strip: true
  
  # Value transformations
  transformations:
    weight:
      - convert_units: "kg"
      - target_format: "number"
    
    date:
      - standardize_format: "%d/%m/%Y"

# Confidence Boosting Rules
confidence_boost:
  # Boost confidence if multiple patterns match
  multiple_match_boost: 0.1
  
  # Boost if field found in expected section
  section_match_boost: 0.15
  
  # Boost if field format is perfect
  format_match_boost: 0.1
  
  # Reduce confidence if field in unexpected location
  location_mismatch_penalty: -0.2

# Fallback Strategy
fallback:
  # If primary patterns fail, try these
  strategies:
    - name: "fuzzy_matching"
      enabled: true
      threshold: 0.8
    
    - name: "keyword_proximity"
      enabled: true
      max_distance: 100
    
    - name: "ml_prediction"
      enabled: false
      model: "field_classifier"