# DocTR Configuration
# Document Text Recognition models

detection:
  model: "db_resnet50"
  # Available: db_resnet50, db_mobilenet_v3_large, linknet_resnet18
  
  input_size: [1024, 1024]
  mean: [0.798, 0.785, 0.772]
  std: [0.264, 0.2749, 0.287]
  
  # Detection parameters
  bin_thresh: 0.3
  box_thresh: 0.1
  assume_straight_pages: true
  preserve_aspect_ratio: true
  symmetric_pad: true

recognition:
  model: "crnn_vgg16_bn"
  # Available: crnn_vgg16_bn, crnn_mobilenet_v3_small, master, sar_resnet31
  
  input_size: [32, 128]  # [height, width]
  mean: [0.694, 0.695, 0.693]
  std: [0.299, 0.296, 0.301]
  
  vocab: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~°£€¥¢฿àâéèêëïîôùûüÿçÀÂÉÈÊËÏÎÔÙÛÜŸÇ "
  
postprocessing:
  # Text post-processing
  resolve_lines: true
  resolve_blocks: true
  paragraph_break: 0.035
  
  # Geometry parameters
  export_as_straight_boxes: false
  
performance:
  batch_size: 2
  device: "auto"
  num_workers: 0
  
  # Optimization
  use_half_precision: false
  compile_model: false

output:
  return_words: true
  return_lines: true
  return_blocks: true
  include_confidence: true
  min_confidence: 0.5