# TableNet Configuration
# Model for table detection and structure recognition

model:
  name: "tablenet"
  architecture: "TableNet"
  backbone: "vgg19"
  pretrained_backbone: true
  
input:
  image_size: [1024, 768]  # [height, width]
  channels: 3
  normalize: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

output:
  num_classes: 2  # table/non-table
  detection_threshold: 0.5
  min_table_area: 1000  # minimum pixels for valid table
  
training:
  batch_size: 4
  learning_rate: 0.0001
  optimizer: "adam"
  weight_decay: 0.00001
  epochs: 100
  
augmentation:
  enabled: true
  random_rotation: 10
  random_scale: [0.8, 1.2]
  random_crop: true
  horizontal_flip: 0.5
  
postprocessing:
  use_morphology: true
  kernel_size: 5
  remove_noise: true
  smooth_edges: true

performance:
  use_mixed_precision: true
  gradient_accumulation_steps: 1
  pin_memory: true
  num_workers: 4